apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-config
  namespace: 5g-testbed
data:
  gnb.yaml: |
    mcc: '001'
    mnc: '01'
    nci: '0x000000010'
    idLength: 32
    linkIp: 0.0.0.0
    ngapIp: 0.0.0.0
    gtpIp: 0.0.0.0
    amfConfigs:
    - address: open5gs-amf.5g-testbed.svc.cluster.local
      port: 38412
    slices:
    - sst: 1
    tac: 1
    ignoreStreamIds: true

  ue.yaml: |
    supi: 'imsi-001010000000001'
    mcc: '001'
    mnc: '01'
    key: 'fec86ba6eb707ed08ce33ae45b4a0fba'
    op: 'c42449363464e2e4fa8adca3063168ca'
    opType: 'OPC'
    amf: '8000'
    imei: '356938035643800'
    imeiSv: '4370816125816151'
    gnbSearchList:
    - ueransim-gnb.5g-testbed.svc.cluster.local
    uacAic:
      mps: false
      mcs: false
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
    sessions:
    - type: 'IPv4'
      apn: 'internet'
      slice:
        sst: 1
    configured-nssai:
    - sst: 1
    default-nssai:
    - sst: 1
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA0: true
      EA1: true
      EA2: true
      EA3: true
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'

  ue2.yaml: |
    supi: 'imsi-001010000000002'
    mcc: '001'
    mnc: '01'
    key: 'fec86ba6eb707ed08ce33ae45b4a0fba'
    op: 'c42449363464e2e4fa8adca3063168ca'
    opType: 'OPC'
    amf: '8000'
    imei: '356938035643801'
    imeiSv: '4370816125816151'
    gnbSearchList:
    - ueransim-gnb.5g-testbed.svc.cluster.local
    uacAic:
      mps: false
      mcs: false
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
    sessions:
    - type: 'IPv4'
      apn: 'internet'
      slice:
        sst: 1
    configured-nssai:
    - sst: 1
    default-nssai:
    - sst: 1
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA0: true
      EA1: true
      EA2: true
      EA3: true
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
